## Book Recommendation system using Clustering and Collabrative based filtering Technique

In [92]:
import pandas as pd
import numpy as np

In [3]:
books = pd.read_csv(
    "C:\\Users\\HP-PC\\OneDrive\\Documents\\Data Science\\Book Recommendation dataset\\BX-Books.csv",
    sep=";",
    encoding="latin-1",
    on_bad_lines="skip"  # Skips problematic rows
)

C:\Users\HP-PC\AppData\Local\Temp\ipykernel_13936\4128285457.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv(

In [4]:
books.columns

Index(['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-S', 'Image-URL-M', 'Image-URL-L'],
      dtype='object')

In [5]:
books = books[['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher','Image-URL-L']]

In [6]:
books

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...
...,...,...,...,...,...,...
271355,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...
271356,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...
271357,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...
271358,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...
271359,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...

In [7]:
books.rename(columns = {'Book-Title': 'Title', 'Book-Author' : 'Author',  'Year-Of-Publication': 'Year', 'Image-URL-L': 'Image'}, inplace = True )

In [8]:
users = pd.read_csv(r"C:\Users\HP-PC\OneDrive\Documents\Data Science\Book Recommendation dataset\BX-Users.csv", sep=";",
    encoding="latin-1",
    on_bad_lines="skip"  # Skips problematic rows
)

In [9]:
users

        User-ID                            Location   Age
0             1                  nyc, new york, usa   NaN
1             2           stockton, california, usa  18.0
2             3     moscow, yukon territory, russia   NaN
3             4           porto, v.n.gaia, portugal  17.0
4             5  farnborough, hants, united kingdom   NaN
...         ...                                 ...   ...
278853   278854               portland, oregon, usa   NaN
278854   278855  tacoma, washington, united kingdom  50.0
278855   278856           brampton, ontario, canada   NaN
278856   278857           knoxville, tennessee, usa   NaN
278857   278858                dublin, n/a, ireland   NaN

[278858 rows x 3 columns]

In [10]:
ratings = pd.read_csv(r"C:\Users\HP-PC\OneDrive\Documents\Data Science\Book Recommendation dataset\BX-Book-Ratings.csv", sep=";",
    encoding="latin-1",
    on_bad_lines="skip"  # Skips problematic rows
    )

In [11]:
ratings

         User-ID         ISBN  Book-Rating
0         276725   034545104X            0
1         276726   0155061224            5
2         276727   0446520802            0
3         276729   052165615X            3
4         276729   0521795028            6
...          ...          ...          ...
1149775   276704   1563526298            9
1149776   276706   0679447156            0
1149777   276709   0515107662           10
1149778   276721   0590442449           10
1149779   276723  05162443314            8

[1149780 rows x 3 columns]

In [12]:
ratings.rename(columns = {'User-ID':'user_id', 'Book-Rating' :'book_rating'}, inplace = True)

In [13]:
x = ratings['user_id'].value_counts()>200

In [14]:
x

user_id
11676      True
198711     True
153662     True
98391      True
35859      True
          ...
116180    False
116166    False
116154    False
116137    False
276723    False
Name: count, Length: 105283, dtype: bool

In [15]:
y= x[x].index

In [16]:
y

Index([ 11676, 198711, 153662,  98391,  35859, 212898, 278418,  76352, 110973,
       235105,
       ...
       260183,  73681,  44296, 155916,   9856, 274808,  28634,  59727, 268622,
       188951],
      dtype='int64', name='user_id', length=899)

In [17]:
ratings = ratings[ratings['user_id'].isin(y)]

In [18]:
ratings

         user_id        ISBN  book_rating
1456      277427  002542730X           10
1457      277427  0026217457            0
1458      277427  003008685X            8
1459      277427  0030615321            0
1460      277427  0060002050            0
...          ...         ...          ...
1147612   275970  3829021860            0
1147613   275970  4770019572            0
1147614   275970   896086097            0
1147615   275970  9626340762            8
1147616   275970  9626344990            0

[526356 rows x 3 columns]

In [19]:
rwb = ratings.merge(books, on = "ISBN")

In [20]:
num_rating = rwb.groupby('Title')['book_rating'].count().reset_index()

In [21]:
num_rating = num_rating.rename(columns = {'book_rating':'num_of_rating'})

In [22]:
num_rating

                                                    Title  num_of_rating
0        A Light in the Storm: The Civil War Diary of ...              2
1                                   Always Have Popsicles              1
2                    Apple Magic (The Collector's series)              1
3        Beyond IBM: Leadership Marketing and Finance ...              1
4        Clifford Visita El Hospital (Clifford El Gran...              1
...                                                   ...            ...
160264  Ãƒ?Ã‚?ber die Pflicht zum Ungehorsam gegen den S...              3
160265                                      Ãƒ?Ã‚?lpiraten.              1
160266                     Ãƒ?Ã‚?rger mit Produkt X. Roman.              1
160267                              Ãƒ?Ã‚?stlich der Berge.              1
160268                                  Ãƒ?Ã‚?thique en toc              1

[160269 rows x 2 columns]

In [23]:
final_rating = rwb.merge(num_rating, on = 'Title')

In [24]:
final_rating.shape

(487671, 9)

In [25]:
final_rating = final_rating[final_rating['num_of_rating']>=50]

In [26]:
final_rating.drop_duplicates(['user_id', 'Title'], inplace = True)

In [27]:
final_rating.shape

(59850, 9)

In [28]:
book_pivot = final_rating.pivot_table(columns = 'user_id', index = 'Title', values = 'book_rating')

In [29]:
final_rating.columns

Index(['user_id', 'ISBN', 'book_rating', 'Title', 'Author', 'Year',
       'Publisher', 'Image', 'num_of_rating'],
      dtype='object')

In [30]:
book_pivot

user_id,254,2276,2766,2977,3363,3757,4017,4385,6242,6251,...,274004,274061,274301,274308,274808,275970,277427,277478,277639,278418
Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
1st to Die: A Novel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2nd Chance,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
4 Blondes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84 Charing Cross Road,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,7.0,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
You Belong To Me,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
Zoya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"\O\"" Is for Outlaw""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
book_pivot.fillna(0, inplace = True)

In [32]:
from scipy.sparse import csr_matrix

In [33]:
book_sparse = csr_matrix(book_pivot)

In [66]:
from sklearn.neighbors import NearestNeighbors

In [68]:
model =  NearestNeighbors(algorithm = 'brute')

In [70]:
model.fit(book_sparse)

NearestNeighbors(algorithm='brute')

In [76]:
distance, suggestion = model.kneighbors(book_pivot.iloc[237,:].values.reshape(1,-1), n_neighbors = 6)

In [78]:
distance

array([[ 0.        , 67.75691847, 68.05145112, 72.277244  , 75.81556568,
        76.30203143]])

In [82]:
for i in range(len(suggestion)):
    print(book_pivot.index[suggestion[i]])

Index(['Harry Potter and the Chamber of Secrets (Book 2)',
       'Harry Potter and the Goblet of Fire (Book 4)',
       'Harry Potter and the Prisoner of Azkaban (Book 3)',
       'Harry Potter and the Sorcerer's Stone (Book 1)', 'Exclusive',
       'The Cradle Will Fall'],
      dtype='object', name='Title')

In [86]:
book_name = book_pivot.index

In [90]:
import pickle
pickle.dump(model,open(r'C:\Users\HP-PC\OneDrive\Documents\Data Science\Book Recommendation Project\artifacts\model.pkl','wb'))
pickle.dump(book_name,open(r'C:\Users\HP-PC\OneDrive\Documents\Data Science\Book Recommendation Project\artifacts\book_name.pkl','wb'))
pickle.dump(final_rating,open(r'C:\Users\HP-PC\OneDrive\Documents\Data Science\Book Recommendation Project\artifacts\final_rating.pkl','wb'))
pickle.dump(book_pivot,open(r'C:\Users\HP-PC\OneDrive\Documents\Data Science\Book Recommendation Project\artifacts\book_pivot.pkl','wb'))

In [102]:
def recommend_book(book_name):
    book_id = np.where(book_pivot.index == book_name)[0][0]
    distance, suggestion = model.kneighbors(book_pivot.iloc[book_id,:].values.reshape(1,-1), n_neighbors = 6)

    for i in range(len(suggestion)):
        books = book_pivot.index[suggestion[i]]
        for j in books:
            print(j)

In [104]:
book_name = 'A Bend in the Road'
recommend_book(book_name)

A Bend in the Road
Exclusive
The Cradle Will Fall
No Safe Place
Family Album
Lake Wobegon days